// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Larach.Entities
{
    public partial class tbMetodospago
    {
        public tbMetodospago()
        {
            tbVentasEncabezado = new HashSet<tbVentasEncabezado>();
        }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        public int MtPag_Id { get; set; }
        public string MtPag_Descripcion { get; set; }
        public int MtPag_UsuarioCreacion { get; set; }
        public DateTime MtPag_FechaCreacion { get; set; }
        public int? MtPag_UsuarioModificacion { get; set; }   
        public bool? MtPag_Estado { get; set; }
        public DateTime? MtPag_FechaModificacion { get; set; }
        public virtual ICollection<tbVentasEncabezado> tbVentasEncabezado { get; set; }
    }
}