// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Larach.Entities
{
    public partial class tbMetodospago
    {
        public tbMetodospago()
        {
            tbVentasEncabezado = new HashSet<tbVentasEncabezado>();
        }

        public int MtPag_Id { get; set; }
        public string MtPag_Descripcion { get; set; }

        public virtual ICollection<tbVentasEncabezado> tbVentasEncabezado { get; set; }
    }
}