// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Larach.Entities
{
    public partial class tbUnidades
    {
        public tbUnidades()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int Unida_Id { get; set; }
        public string Unida_Descripcion { get; set; }
        public int Unida_UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        public DateTime Unida_FechaCreacion { get; set; }
        public int? Unida_UsuarioModificacion { get; set; }
        public DateTime? Unida_FechaModificacion { get; set; }
        public bool? Unida_Estado { get; set; }

        public virtual tbUsuarios Unida_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Unida_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}